### ISSUE TITLE
Labels missing in log record

### ISSUE THREAD

**Issue by MartinAltmayer** [fabric8io/fluent-plugin-kubernetes_metadata_filter#142]
For some of my pods no Kubernetes labels are reported in the logs (record.kubernetes.labels does not exist) although the pod is labelled. It seems to happen mostly to short-running pods.

Unfortunately, my fluentd config processes logs based on labels (I am using kube-fluentd-operator), which fails if the labels are absent.

The test-pod I use to (sometimes) reproduce the issue is the following:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
  labels:
    component: logging-test
spec:
  parallelism: 5  # Not necessary
  completions: 5  # but might help to reproduce the issue
  template:
    metadata:
      labels:
        component: logging-test
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: <some image>
        imagePullPolicy: Always
        command: ['bash']
        args:
          - '-c'
          - |
            set -eu
            echo "Hallo Delta!"
            sleep 10s
            echo "Ciao Delta!"
```

Is there any debug/logging output I can provide to help you understand this issue?

I've also seen https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/123 but as I use v2.1.2 this should be no problem anymore.
