### ISSUE TITLE
More Logging please

### ISSUE THREAD

**Issue by JeremyMarshall** [fabric8io/fluent-plugin-kubernetes_metadata_filter#159]
Love the plugin and got it working on windows containers

I think the documentation should make clear that things like `docker.container_id` is really `record["docker"]["container_id"]`

More logging around the kube  URL would be good and maybe a note about using `kubectl proxy` to avoid certs and https

I built a plugin (currently proprietary) which processes the `config.v2.json` file which lives in the `.../docker/containers/<docker-id>/` on windows which is JSON with includes  the 4 required fields in it to get the metadata - except `container_name` which is set as `POD` as windows only uses the docker_id as its log name (go figure)

**Comment by richm** [comment]
patches welcome

**Comment by kgeorga** [comment]
@JeremyMarshall I am trying to make it work with windows containers myself and failing at the moment - it doesn't seem to add any metadata although the pod seems to have the correct service account.

Do you have any documentation around this or a sample config anywhere? I appreciate this thread is now one year old but any help would be much appreciated!

**Comment by JeremyMarshall** [comment]
I got this working by writing a new plugin - sadly that wasn't allowed to
be open sourced

So the windows nodes use a different file structure (from memory) where
they just have `log-dir/id/id.json` or something like that. There is also a
second file in the `id` directory with metadata in it in json format.

 My plugin cached the metadata and then populated fields in the log record
so the actual kube plugin could do its thing.

I think I used `lookup_from_k8s_field`

 I'll have another go at getting it open-sourced

**Comment by kgeorga** [comment]
@JeremyMarshall thank you for the reply. In the end I managed to get it working on a windows pod - the issue is like you say the location of the logs.

In short, on Linux the path to the logs is /var/log/containers/*.log and the log names carry some information that the plugin uses (namespace,pod etc) - these are actually symlinks to /var/log/pods/  which in turn have more symlinks pointing to /var/lib/docker/containers/<container id>/<container id>-json.log. 

On Windows I found docker logs in C:\ProgramData\docker\containers\<container id>\<container id>-json.log and figured that was it (this is probably the path that you're alluding to). When you point Fluentd on Windows to this path the plugin doesn't work because there is no info on the filename.

However, it seems that Docker on Windows actually uses the exact same paths as on Linux with the same symlinks ending in C:\ProgramData\docker\containers\<container id>\<container id>-json.log. However this being windows the C:\var\log\containers and C:\var\log\pods are hidden on the filesystem 🤦‍♂- they are there nevertheless!

So in the end the way to make this work is to mount all of these host directories on the pod (yes all of them as symlinks don't work the same way as in Linux apparently) and point your Fluentd configuration at /var/log/containers/*.log as you would do on a Linux pod. Something like:

pod yaml:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: fluent-es-windows
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: fluentd-elasticsearch-windows
    helm.sh/chart: fluentd-elasticsearch-2.8.1
  name: fluent-es-fluentd-elasticsearch-windows
  namespace: logging
spec:
  containers:
  - env:
    - name: FLUENTD_ARGS
      value: --no-supervisor -q
    - name: OUTPUT_HOST
      value: elasticsearch-elasticsearch-cluster
    - name: OUTPUT_PORT
      value: "9200"
    - name: OUTPUT_USER
    - name: OUTPUT_PASSWORD
    - name: LOGSTASH_PREFIX
      value: logstash
    - name: OUTPUT_SCHEME
      value: http
    - name: OUTPUT_SSL_VERSION
      value: TLSv1_2
    - name: OUTPUT_BUFFER_CHUNK_LIMIT
      value: 2M
    - name: OUTPUT_BUFFER_QUEUE_LIMIT
      value: "8"
    - name: FLUENTD_ARGS
      value: --no-supervisor -v
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: thameswater.azurecr.io/ops/fluentd-windows
    imagePullPolicy: Always
    name: fluent-es-fluentd-elasticsearch-windows
    volumeMounts:
    - mountPath: C:\k
      name: ck
    - mountPath: C:\var\log\containers
      name: cvarlogcontainers
      readOnly: true
    - mountPath: C:\var\log\pods
      name: cvarlogpods
      readOnly: true
    - mountPath: C:\ProgramData\docker\containers
      name: cprogramdatadockercontainers
      readOnly: true
    - mountPath: C:\fluent\etc\
      name: config-volume
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeSelector:
    beta.kubernetes.io/os: windows
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  serviceAccount: fluent-es-fluentd-elasticsearch
  serviceAccountName: fluent-es-fluentd-elasticsearch
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - hostPath:
      path: C:\k
      type: ""
    name: ck
  - hostPath:
      path: C:\var\log\containers
      type: ""
    name: cvarlogcontainers
  - hostPath:
      path: C:\var\log\pods
      type: ""
    name: cvarlogpods
  - hostPath:
      path: C:\ProgramData\docker\containers
      type: ""
    name: cprogramdatadockercontainers
  - configMap:
      defaultMode: 420
      name: fluent-es-fluentd-elasticsearch-windows
    name: config-volume
  - name: fluent-es-fluentd-elasticsearch-token-96stj
    secret:
      defaultMode: 420
      secretName: fluent-es-fluentd-elasticsearch-token-96stj
```

Hope this helps!
