### ISSUE TITLE
make container_id optional

### ISSUE THREAD

**Issue by eddycharly** [fabric8io/fluent-plugin-kubernetes_metadata_filter#188]
Sometimes it is not possible to retrieve `container_id` from a tag (eg when a custom regex is used and the tag doesn't container this information).

This is because the k8s downward api doesn't provide a solution to access the container_id so there's no easy way to produce a log file containing such an information.

Namespace, pod name and container name are available trough the downward api though.

It would be nice if the `container_id` could be made optional in the filter so that if it is not present, the filter still adds the metadata extracted from namespace, pod name, and container name but omits the container_id.

**Comment by richm** [comment]
> Sometimes it is not possible to retrieve container_id from a tag (eg when a custom regex is used and the tag doesn't container this information).

Under what circumstances does the tag not contain this information?  Can you give us an example?

**Comment by eddycharly** [comment]
let's say i have this kind of pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: container1
    env:
      - name: POD_NAMESPACE
         valueFrom:
           fieldRef:
             fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
    image: ...
    volumeMounts:
    - name: app-logs
      mountPath: /tmp/logs
      subPathExpr: $(POD_NAMESPACE)/$(POD_NAME)/container1
  restartPolicy: Never
  volumes:
  - name: app-logs
    hostPath:
      path: /tmp/app-logs
```

as you can see, we can easily create a folder for each container to write its logs, and the path of this folder will be <namespace name>/<pod name>/<container name>.

with this in mind, the fluentd pipeline could tail the container logs and add the kubernetes metadata, but without making the container id optional it's not possible because we cannot retrieve this information easily from the kubernetes api.

**Comment by richm** [comment]
I don't mean to be picky, asking a lot of questions, but I'm trying to understand if this is an important use case for us and other users.

I have never seen this use case before - can you explain why you are doing this, instead of having the app write to stdout/stderr, or using some sort of sidecar container running in the pod to tail to the log files to stdout/stderr?

**Comment by eddycharly** [comment]
The container I’m working with outputs logs to files (one file per log channel), and the sidecar solution is too limited (it doesn’t work for initContainers, sidecars don’t play well with jobs, etc).

It would be simpler if I could use stdout but unfortunately i can’t. 

From my understanding, the fluentd plugin doesn’t care about stderr or stdout, it just parses the tag. If the user can provide a tag that makes sense it’s up to the user to setup the correct configuration.

**Comment by richm** [comment]
Ok, I see, thanks for explaining.  Not sure when we will get around to fixing this.  Patches are welcome.

**Comment by eddycharly** [comment]
I’ll try to contribute but my ruby knowledge is not that great...
You will have to check the pull request thoroughly 😉

**Comment by eddycharly** [comment]
@richm in the end i found a workaround so i will close the issue
i used the POD_UID from the k8s downward api.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: container1
    env:
      - name: POD_NAMESPACE
         valueFrom:
           fieldRef:
             fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: POD_UID
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.uid
    image: ...
    volumeMounts:
    - name: app-logs
      mountPath: /tmp/logs
      subPathExpr: $(POD_NAMESPACE)/$(POD_NAME)/container1/$(POD_UID)
  restartPolicy: Never
  volumes:
  - name: app-logs
    hostPath:
      path: /tmp/app-logs
```

this way the tag doesn't contain the real `container_id` but the key is unique across pods and it works as expected.
