### ISSUE TITLE
undefined method `each' for nil:NilClass for new pods

### ISSUE THREAD

**Issue by juliantaylor** [fabric8io/fluent-plugin-kubernetes_metadata_filter#310]
with the 2.9.0 version one gets lots of warning outpuds pretty much every time a new pod starts:

    fluentd-cluster-logging-pzw4m fluentd-logging 2021-09-28 07:46:42 +0000 [warn]: parsing container meta information failed for: testing-qa/-test-6d8cbd8555-vx55l: undefined method `each' for nil:NilClass

and

    fluentd-cluster-logging-hldcd fluentd-logging 2021-09-28 08:09:34 +0000 [warn]: #0 parsing container meta information failed for: ams-testing-qa/-qa-5486cbfcfd-d468t: undefined method `sub' for nil:NilClass

this is probably no regression as the message was changed to warning in 2.9.0
the error occurs here:

https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/d96622ed23c8ec6ad9c52a4c4d9c2bbf4dfdbd3d#diff-06faf62948d283e7de8978dee03a0f28ef58256693344f90ea330728f29f1fb3R74

**Comment by juliantaylor** [comment]
that a container in creating phase has no container id for the sub to work on:

```
  - image: internal/...
    imageID: ""
    lastState:
   ...
    name: test
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
```

I assume the failure on each may be during the pending state when it has not been scheduled yet and there is not even a containerstatus field
