### ISSUE TITLE
host metadata

### ISSUE THREAD

**Issue by jchauncey** [fabric8io/fluent-plugin-kubernetes_metadata_filter#9]
Im not capturing the host metadata in my local testing environment. Do I need to enable something to get that information?

**Comment by jimmidyson** [comment]
I've just checked & that only looks like it's added if you set the `kubernetes_url` config param. It comes from the pod spec retrieved from the api server.

**Comment by jchauncey** [comment]
Ah k yeah I have the k8s api set but I'm getting null for that value in the
logs. I'll investigate further. Thanks

**Comment by jimmidyson** [comment]
It gets the host value from the get pods - should be able to see it in `kubectl get pods <podName> -oyaml` & look for `spec.host` (nested object so just it will be on separate lines).

If it doesn't show that can you share the YAML for the pod so I can see what's wrong & try to fix?

**Comment by jchauncey** [comment]
```
spec:
  containers:
  - args:
    - start
    - web
    env:
    - name: PORT
      value: "5000"
    - name: SLUG_URL
      value: http://10.100.115.0:9000/git/home/foo:git-0bcdbff30f986e0cdea5c3f427e6a174fac5ca3b/push/slug.tgz
    - name: DEBUG
      value: "1"
    - name: DEIS_APP
      value: foo
    - name: DEIS_RELEASE
      value: v2
    - name: DOCKERIMAGE
      value: "1"
    image: quay.io/deisci/slugrunner:v2-beta
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 1
    name: foo-web
    readinessProbe:
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/run/secrets/object/store
      name: minio-user
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-g4s5i
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: 192.168.64.2
  restartPolicy: Always
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: minio-user
    secret:
      secretName: minio-user
  - name: default-token-g4s5i
    secret:
      secretName: default-token-g4s5i
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: Ready
  containerStatuses:
  - containerID: docker://8d1b4dde9d7e0e3323571179f1617c67d7377559a6214f255e286d3f222ca636
    image: quay.io/deisci/slugrunner:v2-beta
    imageID: docker://bfc3e9335c6bd79659da5db384cc887a277bbe3d085e6962d5073d2dbbcb7428
    lastState: {}
    name: foo-web
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2016-01-15T20:37:24Z
  hostIP: 192.168.64.2
  phase: Running
  podIP: 172.17.0.16
  startTime: 2016-01-15T20:36:52Z
```
